# Generated by Django 3.2.16 on 2022-12-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('determinations', '0014_auto_20220927_1604'),
        ('determinations', '0015_alter_determinationformsettings_options'),
    ]

    operations = [
    ]
