# Generated by Django 3.2.13 on 2022-09-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0062_remove_payment_requests_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='visibility',
            field=models.CharField(choices=[('applicant', 'Applicant(s)'), ('team', 'Staff'), ('reviewers', 'Reviewers and staff'), ('partners', 'Partners and staff'), ('all', 'Everyone but applicants')], default='all', max_length=30),
        ),
    ]
