# Generated by Django 3.2.15 on 2022-09-01 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0063_alter_activity_visibility'),
        ('activity', '0063_alter_event_type'),
    ]

    operations = [
    ]
