# Generated by Django 3.2.15 on 2022-09-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0064_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='visibility',
            field=models.CharField(choices=[('applicant', 'Applicant(s)'), ('team', 'Staff'), ('reviewers', 'Reviewers and staff'), ('partners', 'Partners and staff'), ('all', 'Everyone but applicants')], default='all', max_length=30),
        ),
    ]
