# Generated by Django 3.2.16 on 2022-12-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0065_alter_activity_visibility'),
        ('activity', '0065_auto_20221006_1115'),
    ]

    operations = [
    ]
