# Generated by Django 3.2.15 on 2022-09-01 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0025_auto_20220722_0844'),
        ('review', '0025_auto_20220901_1215'),
    ]

    operations = [
    ]
