# Generated by Django 3.2.16 on 2023-03-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0026_auto_20220927_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recommendation',
            field=models.IntegerField(choices=[(0, 'Need More Info'), (1, 'Reject'), (2, 'Weak Reject'), (3, 'Weak Accept'), (4, 'Accept'), (5, 'Strong Accept'), (6, 'N/A - Choose not to answer'), (7, 'N/A - Recuse')], default=0, verbose_name='Recommendation'),
        ),
        migrations.AlterField(
            model_name='review',
            name='visibility',
            field=models.CharField(choices=[('reviewers', 'Reviewers and Staff'), ('private', 'Staff Only')], default='private', max_length=10, verbose_name='Visibility'),
        ),
    ]
