# Generated by Django 3.2.13 on 2022-08-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_add_board_member_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_preference',
            field=models.BooleanField(default=True, verbose_name="Yes, I'd like to receive occasional emails from ARDC about their mission and programs."),
        ),
    ]
