# Generated by Django 3.2.16 on 2022-12-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_projects', '0056_auto_20220927_1604'),
        ('application_projects', '0056_packetfile_created_at'),
    ]

    operations = [
    ]
