# Generated by Django 3.2.15 on 2022-09-01 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0097_auto_20220901_1215'),
        ('funds', '0101_auto_20220722_0844'),
    ]

    operations = [
    ]
