# Generated by Django 3.2.15 on 2022-09-21 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0102_add_projectapprovalform_to_fundbase_labbase'),
        ('funds', '0102_merge_0097_auto_20220901_1215_0101_auto_20220722_0844'),
    ]

    operations = [
    ]
