# Generated by Django 3.2.16 on 2022-12-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0104_auto_20220927_1604'),
        ('funds', '0104_show_deadline'),
    ]

    operations = [
    ]
